apiVersion: wildfly.extraordy.com/v1alpha1
kind: Wildfly
metadata:
  name: example-wildfly
spec:
  size: 1
  image: "docker.io/jboss/wildfly"
  version: "14.0.1.Final"
  cmd:
    - "/opt/jboss/wildfly/bin/standalone.sh"
    - "-b"
    - "0.0.0.0"
  ports:
    - port: 8080
      protocol: tcp
    - port: 8443
      protocol: tcp
